# Generated by Django 5.2.1 on 2025-06-11 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_room_participants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="participants",
            field=models.ManyToManyField(
                related_name="participants", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
